@Restaurants.API_HostAddress = https://localhost:7265
@host = https://localhost
@port = 7265
@token = CfDJ8Nq5SiDl9JZBogTv25K-iBid2wV-Rx0yO6JoiF-2rOdGx2V3vTwze_aAMNFbSPqGjGzsqmNaKBtNqs_PXmoyiUZa4OXQDAEUV7X_zZrm1gNs7MN0ym6ReJoDs6D-fFPvBQsdV7MeTWuWHJ8DoZ3Ma7hKeIb10TNWYP_KYQd6qiIpl64ujTerP8b7fANMqCY4Jim5iRnDeQHXwzvfaWrTgXWMjrWRkjTjHnbbhkleg5r5Z5HlYPgQ32Ug4OgvoD-yOIR_AKbRVfyHdsPmq7BULvtUBooQ8wZtEiY0mS8l3Cy3Qp08u8N_05U6HM7Dr-gNSz0sgceAOLbLKCe2zbK_SzqBomvAk-Z7zgvoRGwexyx-E1G9uJKDF1Elvd2E4UPTXcLjMFY-mUl6YAWoEl4uOTEePkKDqgIFyG8NDwAJ776B5xndZr7_f1OVyOuCrucy_MEwMilPedU_dB0Yvk9MuiLSZkK0S0FVevufqP2-Y1n1PxAyxpv1CIz_aKoOi2zqcDeEzG5wcqvAoYqpIYrr1FVoqL5W5C2N9y0Ijm5t6jzym6C1dxd8tiDlEbDEnntQlTeCK9iQ64R73pKlC_1WiP6tFrEQpvOO5P5S8SdiQtlUWsKp8My8W7YXzYOl0j0qMwJBQ94TWIL75p-wKQ9lTjx0ZEI2-0LI-7ss6EF1R7lV9J0gKuC_DHSE3grxWEeqaV9DlNiXnZCbrpy4oxlXF4_GQrUMg8-71zrMFKTYo49bPZ8jzOv2i2dZgrp9ZgBN8JEdz9Cl6Xdm2yDhc7qmtHUL3_TKAZcAGF0UspXrA74O

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=2&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/200
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Owner2 restaurant2",
  "Description": "A culinary experience like no other",
  "Category": "Mexican",
  "HasDelivery": true,
  "Contact Email": "info@gourmerdeligts.com",
  "Contact Number": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/9
Authorization: Bearer {{token}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1010
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name":"Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 231,
  "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/1

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "owner2@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "owner2@test.com",
  "password": "Password1!"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "Ukraine",
  "DateOfBirth": "2003-11-03"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRoles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
