@Restaurants.API_HostAddress = https://localhost:7265


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/200

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy Delights122",
  "Description": "A culinary experience like no other",
  "Category": "Mexican",
  "HasDelivery": true,
  "Contact Email": "info@gourmerdeligts.com",
  "Contact Number": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/7
Content-Type: application/json

{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###
